title: Ichi
email: shinichirizwan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ini adalah deskripsi singkat untuk blog Jekyll baru saya.
  Anda bisa mengubahnya di _config.yml.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ["_pages"]
header_pages:
  - about.md # Pastikan file 'about.md' ada di folder '_pages/'
  - contact.md # Pastikan file 'contact.md' ada di folder '_pages/'
  - test.md
permalink: /:title/

# -- Build settings --

# Highlight Code
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true # Menampilkan nomor baris pada blok kode
      css_classes: "highlight" # Kelas CSS yang akan digunakan untuk styling
theme: minima # Anda bisa menggunakan tema default atau membuatnya sendiri


# Pengaturan untuk Paginasi Jekyll
paginate: 5 # Jumlah postingan per halaman
paginate_path: "/page:num/" # Struktur URL untuk halaman paginasi (misal: /page2/, /page3/)

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/