title: Ichi
email: shinichirizwan@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Ini adalah deskripsi singkat untuk blog Jekyll baru saya.
  Anda bisa mengubahnya di _config.yml.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
include: ["_pages"]
header_pages:
  - about.md # Pastikan file 'about.md' ada di folder '_pages/'
  - contact.md # Pastikan file 'contact.md' ada di folder '_pages/'
  - test.md
permalink: /:title/


# -- Build settings --

# Highlight Code
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true # Menampilkan nomor baris pada blok kode
      css_classes: "highlight" # Kelas CSS yang akan digunakan untuk styling
theme: minima # Anda bisa menggunakan tema default atau membuatnya sendiri

# Konfigurasi Giscus untuk Komentar
giscus:
  repo: "kucingcupu/kucingcupu.github.io" # Ganti dengan nama user/repo kamu, contoh: "username/your-blog-repo"
  repo_id: "R_kgDOPGfxxg" # Ganti dengan Repo ID dari Giscus.app

  # Kategori default jika artikel tidak memiliki kategori blog atau tidak ada dalam mapping
  default_category_name: "General" # Nama kategori di GitHub Discussions
  default_category_id: "DIC_kwDOPGfxxg4CqPXX" # ID kategori di GitHub Discussions (Dapatkan dari GraphQL Explorer)
  
  # Mapping kategori blog Jekyll ke Giscus GitHub Discussions
  # Sesuaikan dengan kategori blog kamu dan kategori diskusi di GitHub kamu.
  category_mapping:
    - blog_category: "teknologi" # Kategori di front matter artikel Jekyll (harus huruf kecil, tanpa spasi)
      giscus_category_name: "Teknologi Diskusi" # Nama kategori di GitHub Discussions
      giscus_category_id: "DIC_kwDOPGfxxg4CqP2U" # ID kategori di GitHub Discussions
    - blog_category: "gaya-hidup"
      giscus_category_name: "Gaya Hidup Diskusi"
      giscus_category_id: "DIC_kwDOPGfxxg4CqP3A"
    - blog_category: "resep-masakan"
      giscus_category_name: "Resep Masakan Diskusi"
      giscus_category_id: "DIC_kwDOPGfxxg4CqP4B"
    # Tambahkan lebih banyak mapping sesuai kebutuhan blog kamu


# Pengaturan untuk Paginasi Jekyll
paginate: 5 # Jumlah postingan per halaman
paginate_path: "/page:num/" # Struktur URL untuk halaman paginasi (misal: /page2/, /page3/)

plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# files' path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/